In [215]:
import pandas as pd
import numpy as np
import re

In [216]:
nominees = pd.read_csv("oscars.csv", encoding='latin1')

In [217]:
nominees.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,670454353,False,finalized,3,2/10/15 3:45,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,Lewis Milestone,NaN,NaN,NaN,NaN
1,670454354,False,finalized,3,2/10/15 2:03,"Glasgow, Scotland",1.0,2-Feb-1886,1.0,White,...,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,Frank Lloyd,NaN,NaN,NaN,NaN
2,670454355,False,finalized,3,2/10/15 2:05,"Chisinau, Moldova",1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,Lewis Milestone,NaN,NaN,NaN,NaN
3,670454356,False,finalized,3,2/10/15 2:04,"Chicago, Il",1.0,23-Feb-1899,1.0,White,...,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,Norman Taurog,NaN,NaN,NaN,NaN
4,670454357,False,finalized,3,2/10/15 1:48,"Salt Lake City, Ut",1.0,23-Apr-1894,1.0,White,...,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,Frank Borzage,NaN,NaN,NaN,NaN

In [218]:
nominees.shape

(441, 27)

In [219]:
birthPlaces = list(nominees["birthplace"])
for i in range(len(birthPlaces)):
    birthPlaces[i] = re.findall(r'(\w+)$', birthPlaces[i])
print(birthPlaces)

[['Moldova'], ['Scotland'], ['Moldova'], ['Il'], ['Ut'], ['Scotland'], ['Italy'], ['Me'], ['Italy'], ['Ca'], ['Italy'], ['Ca'], ['Me'], ['Me'], ['France'], ['Hungary'], ['Ca'], ['City'], ['Austria'], ['France'], ['Turkey'], ['Mo'], ['Pa'], ['Pa'], ['Ca'], ['Me'], ['Austria'], ['Turkey'], ['Ks'], ['Ca'], ['England'], ['Il'], ['France'], ['Austria'], ['In'], ['England'], ['England'], ['City'], ['In'], ['Austria'], ['Germany'], ['Mn'], ['England'], ['England'], ['Japan'], ['Il'], ['Il'], ['Mn'], ['Mi'], ['Czechoslovakia'], ['Il'], ['Ny'], ['City'], ['Tx'], ['Ca'], ['Va'], ['England'], ['Nj'], ['Czechoslovakia'], ['In'], ['City'], ['Italy'], ['Md'], ['City'], ['Ca'], ['Ny'], ['Ca'], ['Oh'], ['Il'], ['Ny'], ['England'], ['Canada'], ['Oh'], ['England'], ['Ga'], ['Ok'], ['France'], ['Zealand'], ['Ca'], ['Taiwan'], ['Ny'], ['Mn'], ['England'], ['Ca'], ['England'], ['France'], ['Taiwan'], ['Switzerland'], ['Oh'], ['England'], ['Pa'], ['Mo'], ['England'], ['Oh'], ['England'], ['Ukraine'], ['Wi'], ['Wi'], ['England'], ['Pa'], ['Mt'], ['Ny'], ['Hungary'], ['Wa'], ['Wales'], ['Wi'], ['England'], ['England'], ['Pa'], ['Rico'], ['City'], ['Mt'], ['Il'], ['Ne'], ['Ct'], ['Russia'], ['England'], ['England'], ['Il'], ['City'], ['Austria'], ['Ca'], ['Fl'], ['England'], ['City'], ['England'], ['Ny'], ['Ca'], ['Ia'], ['Va'], ['Ca'], ['Ne'], ['Ma'], ['Ny'], ['City'], ['England'], ['Ny'], ['Ny'], ['Ca'], ['City'], ['Ne'], ['England'], ['Ca'], ['Pa'], ['Dc'], ['Oh'], ['Nj'], ['Ca'], ['England'], ['England'], ['Wales'], ['City'], ['Ca'], ['Ca'], ['Ca'], ['Australia'], ['City'], ['Italy'], ['Nj'], ['Zealand'], ['Ny'], ['City'], ['Ca'], ['Tx'], ['Ny'], ['Tx'], ['England'], ['Ca'], ['Ca'], ['England'], ['France'], ['England'], ['Tx'], ['Ma'], ['Austria'], ['Ma'], ['Nj'], ['Ma'], ['England'], ['Ok'], ['Ga'], ['Ireland'], ['City'], ['Canada'], ['Wales'], ['Canada'], ['Oh'], ['Russia'], ['Il'], ['Mexico'], ['Nj'], ['City'], ['Ma'], ['Mexico'], ['City'], ['Il'], ['Wales'], ['England'], ['Oh'], ['Ct'], ['Ga'], ['England'], ['Ny'], ['City'], ['City'], ['Ma'], ['Mn'], ['England'], ['Ok'], ['Oh'], ['Romania'], ['City'], ['City'], ['Il'], ['Il'], ['Ny'], ['Ga'], ['Ca'], ['England'], ['Ny'], ['City'], ['Cambodia'], ['Wi'], ['England'], ['Scotland'], ['Mo'], ['Ny'], ['Nj'], ['Pa'], ['Ca'], ['Tx'], ['Ny'], ['Nj'], ['Ny'], ['Il'], ['Ne'], ['England'], ['Rico'], ['England'], ['Mo'], ['Ca'], ['Tn'], ['Ky'], ['Ny'], ['Islands'], ['Australia'], ['Na'], ['Wales'], ['Canada'], ['Na'], ['La'], ['Pa'], ['Canada'], ['Canada'], ['Canada'], ['Dc'], ['Ct'], ['France'], ['Ma'], ['Germany'], ['Germany'], ['Ma'], ['India'], ['Mo'], ['Japan'], ['England'], ['Ok'], ['Sweden'], ['Tx'], ['Japan'], ['Ut'], ['Mo'], ['Japan'], ['City'], ['India'], ['City'], ['Belgium'], ['Pa'], ['Italy'], ['Sweden'], ['Ga'], ['Ny'], ['Germany'], ['England'], ['Italy'], ['Ny'], ['Ky'], ['England'], ['India'], ['England'], ['Ct'], ['Ny'], ['Ct'], ['England'], ['England'], ['City'], ['Ca'], ['England'], ['Mi'], ['Al'], ['Fl'], ['Ca'], ['City'], ['Ca'], ['Tx'], ['Ct'], ['Nj'], ['Va'], ['Ca'], ['Mo'], ['Il'], ['Ca'], ['Ca'], ['England'], ['Tn'], ['Ca'], ['England'], ['Ga'], ['Mn'], ['Ny'], ['Il'], ['Ca'], ['Ca'], ['Ne'], ['Ga'], ['Oh'], ['Hi'], ['Africa'], ['Ne'], ['La'], ['England'], ['France'], ['England'], ['Va'], ['Israel'], ['Nj'], ['Ky'], ['Australia'], ['Mn'], ['City'], ['Ca'], ['Ks'], ['Mo'], ['Il'], ['City'], ['Greece'], ['Pa'], ['City'], ['In'], ['City'], ['City'], ['Il'], ['Ma'], ['Mi'], ['Ca'], ['Ia'], ['Nj'], ['Ca'], ['Il'], ['Japan'], ['England'], ['Mo'], ['Pa'], ['Rico'], ['Ny'], ['England'], ['Russia'], ['Mo'], ['Ne'], ['Ma'], ['Ma'], ['Md'], ['Dc'], ['Ia'], ['Oh'], ['Ca'], ['Sweden'], ['City'], ['Ny'], ['England'], ['England'], ['Nj'], ['Ar'], ['Ny'], ['Mn'], ['Nj'], ['England'], ['Ca'], ['Mo'], ['Ma'], ['Ma'], ['Ireland'], ['City'], ['Ny'], ['Ny'], ['Canada'], ['Mo'], ['Nj'], ['France'], ['Ga'], ['England'], ['Ca'], ['Ca'], ['Ny'], ['Wales'], ['Tx'], ['Australia'], ['England'], ['Il'], ['England'], ['Spain'], ['Md'], ['City'], ['Al'], ['Ny'], ['Mexico'], ['Austria'], ['Mo'], ['Ca'], ['City'], ['Il'], ['Ca'], ['City'], ['City'], ['Fl'], ['Ok'], ['Ga'], ['Mt'], ['England'], ['Ne'], ['Ne'], ['Ca'], ['Ma'], ['Md'], ['Ca'], ['England'], ['England'], ['England'], ['Il'], ['Ne'], ['Mo']]

In [226]:
for i in range(len(birthPlaces)):
    nominees.loc[[i], "birthplace"] = birthPlaces[i]
    #nominees = nominees.replace(nominees["birthplace"][i], birthPlaces[i][0])

In [227]:
nominees.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
0,670454353,False,finalized,3,2/10/15 3:45,Moldova,1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,Two Arabian Knights,Lewis Milestone,NaN,NaN,NaN,NaN
1,670454354,False,finalized,3,2/10/15 2:03,Scotland,1.0,2-Feb-1886,1.0,White,...,Best Director,http://www.nndb.com/people/626/000042500/,NaN,NaN,The Divine Lady,Frank Lloyd,NaN,NaN,NaN,NaN
2,670454355,False,finalized,3,2/10/15 2:05,Moldova,1.0,30-Sep-1895,1.0,White,...,Best Director,http://www.nndb.com/people/320/000043191/,NaN,NaN,All Quiet on the Western Front,Lewis Milestone,NaN,NaN,NaN,NaN
3,670454356,False,finalized,3,2/10/15 2:04,Il,1.0,23-Feb-1899,1.0,White,...,Best Director,http://www.nndb.com/people/544/000041421/,NaN,NaN,Skippy,Norman Taurog,NaN,NaN,NaN,NaN
4,670454357,False,finalized,3,2/10/15 1:48,Ut,1.0,23-Apr-1894,1.0,White,...,Best Director,http://www.nndb.com/people/292/000044160/,NaN,NaN,Bad Girl,Frank Borzage,NaN,NaN,NaN,NaN

In [228]:
nonUS = nominees["birthplace"]
for i in range(len(nonUS)):
    if len(nonUS[i]) <= 2:
        nonUS.pop(i)
nonUS = list(nonUS)
nonUS

['Moldova',
 'Scotland',
 'Moldova',
 'Scotland',
 'Italy',
 'Italy',
 'Italy',
 'France',
 'Hungary',
 'City',
 'Austria',
 'France',
 'Turkey',
 'Austria',
 'Turkey',
 'England',
 'France',
 'Austria',
 'England',
 'England',
 'City',
 'Austria',
 'Germany',
 'England',
 'England',
 'Japan',
 'Czechoslovakia',
 'City',
 'England',
 'Czechoslovakia',
 'City',
 'Italy',
 'City',
 'England',
 'Canada',
 'England',
 'France',
 'Zealand',
 'Taiwan',
 'England',
 'England',
 'France',
 'Taiwan',
 'Switzerland',
 'England',
 'England',
 'England',
 'Ukraine',
 'England',
 'Hungary',
 'Wales',
 'England',
 'England',
 'Rico',
 'City',
 'Russia',
 'England',
 'England',
 'City',
 'Austria',
 'England',
 'City',
 'England',
 'City',
 'England',
 'City',
 'England',
 'England',
 'England',
 'Wales',
 'City',
 'Australia',
 'City',
 'Italy',
 'Zealand',
 'City',
 'England',
 'England',
 'France',
 'England',
 'Austria',
 'England',
 'Ireland',
 'City',
 'Canada',
 'Wales',
 'Canada',
 'Russia',
 'Mexico',
 'City',
 'Mexico',
 'City',
 'Wales',
 'England',
 'England',
 'City',
 'City',
 'England',
 'Romania',
 'City',
 'City',
 'England',
 'City',
 'Cambodia',
 'England',
 'Scotland',
 'England',
 'Rico',
 'England',
 'Islands',
 'Australia',
 'Wales',
 'Canada',
 'Canada',
 'Canada',
 'Canada',
 'France',
 'Germany',
 'Germany',
 'India',
 'Japan',
 'England',
 'Sweden',
 'Japan',
 'Japan',
 'City',
 'India',
 'City',
 'Belgium',
 'Italy',
 'Sweden',
 'Germany',
 'England',
 'Italy',
 'England',
 'India',
 'England',
 'England',
 'England',
 'City',
 'England',
 'City',
 'England',
 'England',
 'Africa',
 'England',
 'France',
 'England',
 'Israel',
 'Australia',
 'City',
 'City',
 'Greece',
 'City',
 'City',
 'City',
 'Japan',
 'England',
 'Rico',
 'England',
 'Russia',
 'Sweden',
 'City',
 'England',
 'England',
 'England',
 'Ireland',
 'City',
 'Canada',
 'France',
 'England',
 'Wales',
 'Australia',
 'England',
 'England',
 'Spain',
 'City',
 'Mexico',
 'Austria',
 'City',
 'City',
 'City',
 'England',
 'England',
 'England',
 'England']

In [231]:
baris_sebelum = nominees.shape[0]
print("Jumlah nominee sebelumnya adalah {}.".format(baris_sebelum))

nominees = nominees.loc[nominees["birthplace"].isin(nonUS)]

baris_sesudah = nominees.shape[0]
print("Jumlah nominee setelah seleksi {}.".format(baris_sesudah))

print("{} nominee yang dihapus!".format(baris_sebelum-baris_sesudah))

Jumlah nominee sebelumnya adalah 441.

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [186]:
nominees.head()

0    True
1    True
2    True
5    True
6    True
Name: birthplace, dtype: bool